// Code generated by MockGen. DO NOT EDIT.
// Source: internal/provider/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/provider/client.go -destination=internal/provider/mock_provider/client.go
//

// Package mock_provider is a generated GoMock package.
package mock_provider

import (
	io "io"
	reflect "reflect"

	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	gomock "go.uber.org/mock/gomock"
)

// MockProviderHTTPClient is a mock of ProviderHTTPClient interface.
type MockProviderHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockProviderHTTPClientMockRecorder
	isgomock struct{}
}

// MockProviderHTTPClientMockRecorder is the mock recorder for MockProviderHTTPClient.
type MockProviderHTTPClientMockRecorder struct {
	mock *MockProviderHTTPClient
}

// NewMockProviderHTTPClient creates a new mock instance.
func NewMockProviderHTTPClient(ctrl *gomock.Controller) *MockProviderHTTPClient {
	mock := &MockProviderHTTPClient{ctrl: ctrl}
	mock.recorder = &MockProviderHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderHTTPClient) EXPECT() *MockProviderHTTPClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProviderHTTPClient) Create(path string, data io.Reader) ([]byte, diag.Diagnostics) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", path, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(diag.Diagnostics)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProviderHTTPClientMockRecorder) Create(path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProviderHTTPClient)(nil).Create), path, data)
}

// Delete mocks base method.
func (m *MockProviderHTTPClient) Delete(path string) ([]byte, diag.Diagnostics) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(diag.Diagnostics)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockProviderHTTPClientMockRecorder) Delete(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProviderHTTPClient)(nil).Delete), path)
}

// Get mocks base method.
func (m *MockProviderHTTPClient) Get(path string) ([]byte, diag.Diagnostics) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(diag.Diagnostics)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProviderHTTPClientMockRecorder) Get(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProviderHTTPClient)(nil).Get), path)
}

// GetApiEndpoint mocks base method.
func (m *MockProviderHTTPClient) GetApiEndpoint() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiEndpoint")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetApiEndpoint indicates an expected call of GetApiEndpoint.
func (mr *MockProviderHTTPClientMockRecorder) GetApiEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiEndpoint", reflect.TypeOf((*MockProviderHTTPClient)(nil).GetApiEndpoint))
}

// GetWithStatus mocks base method.
func (m *MockProviderHTTPClient) GetWithStatus(path string) ([]byte, diag.Diagnostics, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithStatus", path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(diag.Diagnostics)
	ret2, _ := ret[2].(int)
	return ret0, ret1, ret2
}

// GetWithStatus indicates an expected call of GetWithStatus.
func (mr *MockProviderHTTPClientMockRecorder) GetWithStatus(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithStatus", reflect.TypeOf((*MockProviderHTTPClient)(nil).GetWithStatus), path)
}

// Update mocks base method.
func (m *MockProviderHTTPClient) Update(path string, data io.Reader) ([]byte, diag.Diagnostics) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", path, data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(diag.Diagnostics)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProviderHTTPClientMockRecorder) Update(path, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProviderHTTPClient)(nil).Update), path, data)
}
