// Code generated by MockGen. DO NOT EDIT.
// Source: retry.go
//
// Generated by this command:
//
//	mockgen -source=retry.go -destination=mock_provider/mock_retry.go
//

// Package mock_provider is a generated GoMock package.
package mock_provider

import (
	reflect "reflect"

	diag "github.com/hashicorp/terraform-plugin-framework/diag"
	gomock "go.uber.org/mock/gomock"
)

// MockRetryOperation is a mock of RetryOperation interface.
type MockRetryOperation struct {
	ctrl     *gomock.Controller
	recorder *MockRetryOperationMockRecorder
	isgomock struct{}
}

// MockRetryOperationMockRecorder is the mock recorder for MockRetryOperation.
type MockRetryOperationMockRecorder struct {
	mock *MockRetryOperation
}

// NewMockRetryOperation creates a new mock instance.
func NewMockRetryOperation(ctrl *gomock.Controller) *MockRetryOperation {
	mock := &MockRetryOperation{ctrl: ctrl}
	mock.recorder = &MockRetryOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetryOperation) EXPECT() *MockRetryOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockRetryOperation) Execute() ([]byte, diag.Diagnostics, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(diag.Diagnostics)
	ret2, _ := ret[2].(int)
	return ret0, ret1, ret2
}

// Execute indicates an expected call of Execute.
func (mr *MockRetryOperationMockRecorder) Execute() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockRetryOperation)(nil).Execute))
}
